# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "password123"
      FLASK_APP: app.py